### ISSUE TITLE
Build keretrendszer beüzemelése

### ISSUE THREAD

**Issue by DanielVeress** [BME-MIT-IET/iet-hf-2023-hangolow#4]
Technológia fókusz egyik feladata.
Feladatot végzők: @Andras-T és @DanielVeress

**Comment by DanielVeress** [comment]
commit: 6aa5e08832bdeb9aaaf83fefe318c039b436d559
Működő build keretrendszer

**Comment by Andras-T** [comment]
Java CI with Maven sikeresen beüzemelve
