### ISSUE TITLE
CI/Sonar cloud beüzemelése

### ISSUE THREAD

**Issue by DanielVeress** [BME-MIT-IET/iet-hf-2023-hangolow#5]
Technológia fókusz egyik feladata.
Feladatot végzők: @Andras-T és @DanielVeress

**Comment by Andras-T** [comment]
Sonar cloud sikeresen integrálva

**Comment by Andras-T** [comment]
Felesleges sonar cloud fájlok eltávolítva.

**Comment by DanielVeress** [comment]
Detected bugs are fixed.
