### ISSUE TITLE
BDD tesztek írása

### ISSUE THREAD

**Issue by erikszasz** [BME-MIT-IET/iet-hf-2023-hangolow#6]
BDD tesztek elkészítése CucumberStudio-ban

- User story-k kiválasztása
- Scenario-k létrehozása.
- Tesztek létrehozása
- Tesztek automatizálása és futtatása

**Comment by erikszasz** [comment]
A CucumberStudio projektet felállítottuk. Ez megtalálható az [alábbi linken](https://studio.cucumber.io/projects/385434)(csak engedéllyel érhető el)
![CucumberStudio](https://github.com/BME-MIT-IET/iet-hf-2023-hangolow/assets/50337392/537dd556-845c-4009-a189-93dd319c7e41)

**Comment by DarkTemplar91** [comment]
closes #7

**Comment by DarkTemplar91** [comment]
Closes #7

**Comment by erikszasz** [comment]
A tesztek és a hozzá tartozó lépések elkészültek. Nyitottam egy új pull request-et ehhez: #7
